### ISSUE TITLE
Dosen't work with openwrt 18.06.5 unboud dnsmasq

### ISSUE THREAD

**Issue by cristianmenghi** [kevinoid/kevinlocke.name#3]
Hi, im following the process on 18.06.2 and work nice, but after upgrade to 18.06.5 can't get unbound query dnsmas for my home.intra domain, but if y do a dig directly to the port of dnsmas they response.

thanks in advance.

**Comment by kevinoid** [comment]
Do I understand correctly that you are able to query public domains via Unbound on port 53 (e.g. `dig google.com @192.168.0.1` works) and private domains via dnsmasq on port 53535 (e.g. `dig -p 53535 openwrt.home.intra @192.168.0.1` works) but not private domains via Unbound (e.g. `dig openwrt.home.intra @192.168.0.1` doesn't work)?

If so, I would confirm that `manual_conf` is `1` for `unbound` (using `uci get 'unbound.@unbound[0].manual_conf'` - in case it was reset during upgrade) and that `/etc/unbound/unbound.conf` still contains the `forward-zone`s for your private domain (in case it was renamed or overwritten during upgrade).

If neither of those is the problem, could you provide the output of `uci show unbound`, `uci show 'dhcp.@dnsmasq[0]'`, and the content of `/etc/unbound/unbound.conf`?

**Comment by kevinoid** [comment]
Closing due to lack of info.  Feel free to follow-up or reopen with additional info.
