### ISSUE TITLE
A11y: Sets foreground colors without also setting background colors

### ISSUE THREAD

**Issue by Seirdy** [kevinoid/kevinlocke.name#9]
Setting foreground colors without also setting background colors is problematic because users may customize their browser's default colors to something besides black-on-white. For instance, my browser's default colors are white-on-gray; kevinlocke.name thus renders black text on a gray background for me.

Solution: explicitly set the background color, too.

**Comment by kevinoid** [comment]
Thanks for reporting the issue!  Can you confirm that the only places where this is an issue is in the footer (`#footer`) and links (`a:link` and `.nav a`)?

**Comment by kevinoid** [comment]
Thanks again for reporting the issue.  I've removed the explicit color from links and the footer, and added a color to the warning box.  If you notice any other places where colors are specified which may not work with user agent defaults, don't hesitate to let me know.
